### Signup
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}
