### login
POST http://localhost:3001/auth/login
Content-Type: application/json


{
"email": "admin@example.com",
"password": "pass1234"
}


### get signup list
GET http://localhost:3001/api/signup
Authorization: Bearer {{token}}